### ISSUE TITLE
Set margins size

### ISSUE THREAD

**Issue by v-bulynkin** [EvotecIT/PSWriteOffice#11]
Hello, how to set margins?

I try
```powershell
$doc.Margins.Left = 1
```
but it doesn't work.

Can I set margins preset like 'Narrow'?

**Comment by PrzemyslawKlys** [comment]
```powershell
document.Sections[0].SetMargins(WordMargin.Normal);
```

Sections[0] is basically the first section and it always exists.

![image](https://user-images.githubusercontent.com/15063294/224074637-5206e9c9-37ac-427c-a522-74039aaaca75.png)

```powershell
document.Margins.Type = WordMargin.Narrow;
```

Should also work I guess .

**Comment by v-bulynkin** [comment]
Thank you!

Those works both in Powershell:
```powershell
$doc.Margins.Type = 'Narrow'
# or
$doc.Sections[0].SetMargins('Narrow')
```

And how could I set only left margin, for example, 5cm?
```powershell
$doc.Sections[0].SetMargins(5)
```
works, but I can't understand its logic because no one margin is not equal 5 afterwards.

I'm sorry for asking so many questions but there's no much information and examples in the OfficeIMO repository are not Powershell ones so it's difficult for me to learn from it.

**Comment by v-bulynkin** [comment]
Works with this crutch:
```powershell
function ConvertTo-Twips {
param($cm)
$cm*567 -as [uint32]
}

$docFile = "C:\temp\doc.docx"
rm $docFile
$doc = New-OfficeWord -FilePath $docFile
$doc.PageSettings.PageSize = 'A4'
$doc.Settings.FontFamily = 'Times New Roman'
$doc.Settings.FontFamilyHighAnsi = 'Times New Roman'
$doc.Settings.FontSize = 11
$doc.Sections[0].Margins.Left = ConvertTo-Twips 5
$doc.Sections[0].Margins.Top = ConvertTo-Twips 7

New-OfficeWordText -Document $doc -Text "Hello world"

Save-OfficeWord -Document $doc -Show
```

**Comment by PrzemyslawKlys** [comment]
Cool, I'll see if this could be natively implemented to work with CM, but then I guess some people will want inches... and it never ends :)

**Comment by v-bulynkin** [comment]
It will probably demand to read from operating system's regional parameters.
In the end, you'll write the second Word but for Powershell :)

**Comment by v-bulynkin** [comment]
Autodetect
```powershell
function ConvertTo-Twips {
param($num)
    if ((New-Object System.Globalization.RegionInfo (get-culture).name).IsMetric) {
        $num*567 -as [uint32]
    }
    else {
        $num*1440 -as [uint32]
    }
}
```

**Comment by PrzemyslawKlys** [comment]
It has to be a bit more static. What if you as a developer are given must be 3 inches, but live in Europe.

**Comment by v-bulynkin** [comment]
```powershell
function ConvertTo-Twips {
param($num)
    if ($num -match 'cm$') {
        $n = (($num -replace '\D') -as [uint32])*567 
    }
    elseif ($num -match 'in$') {
        $n = (($num -replace '\D') -as [uint32])*1440
    }
    else {
        Write-Host -fore red "Wrong units!"
    }
}
```
