### ISSUE TITLE
Possible to add images?

### ISSUE THREAD

**Issue by OneFreemanWill** [EvotecIT/PSWriteOffice#17]
Hello,

I noticed a method `$Document.Images.Add`, but not having any luck.

Tried specifying full and relative paths to a jpeg image but I always get error "InvalidOperation: You cannot call a method on a null-valued expression."

Am I doing it wrong, or this feature not yet implemented?

**Comment by PrzemyslawKlys** [comment]
I believe it's AddImage(xx) on Paragraph that works.
