### ISSUE TITLE
What about Outlook or OneNote?

### ISSUE THREAD

**Issue by oliwex** [EvotecIT/PSWriteOffice#2]
What about Outlook or OneNote?
Can module have cmdlets usable in OneNote or Outlook...maybe in future?

**Comment by PrzemyslawKlys** [comment]
Word, Excel, and PowerPoint are based on OpenXML and that's why I have connected them together as they have similar structures and DLL. I am not sure how OneNote or Outlook would make sense, as those would require a separate approach for each one.
